const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

function parseStakeholders(envValue) {
  return envValue
    .split(",")
    .map((address) => address.trim())
    .filter((address) => address.length > 0);
}

function writeVerifyArgs(deploymentsDir, networkName, stakeholders, threshold) {
  const argsPath = path.join(deploymentsDir, `${networkName}-args.js`);
  const contents = `// Auto-generated by scripts/deploy.js\nmodule.exports = [\n  ${JSON.stringify(stakeholders, null, 2)},\n  ${threshold}\n];\n`;
  fs.writeFileSync(argsPath, contents);
  return argsPath;
}

async function main() {
  const { ethers, network } = hre;
  const [deployer, fallback1, fallback2] = await ethers.getSigners();
  const networkName = network.name;

  const stakeholders = process.env.STAKEHOLDERS
    ? parseStakeholders(process.env.STAKEHOLDERS)
    : [deployer.address, fallback1.address, fallback2.address];
  const threshold = Number(process.env.THRESHOLD || "2");

  console.log("=== AgentVault Deployment ===");
  console.log(`Network: ${networkName}`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Stakeholders: ${stakeholders.join(", ")}`);
  console.log(`Threshold: ${threshold}`);

  const AgentVault = await ethers.getContractFactory("AgentVault");
  const vault = await AgentVault.deploy(stakeholders, threshold);
  const deploymentTx = vault.deploymentTransaction();
  if (deploymentTx === null) {
    throw new Error("Deployment transaction was not available");
  }
  console.log(`Deployment tx: ${deploymentTx.hash}`);

  let receipt;
  if (networkName === "sepolia" && deploymentTx !== null) {
    console.log("Waiting for 5 confirmations on Sepolia...");
    receipt = await deploymentTx.wait(5);
  } else {
    receipt = await deploymentTx.wait();
  }

  const address = await vault.getAddress();
  if (receipt === null) {
    throw new Error("Deployment receipt was not available");
  }

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });

  const deployment = {
    address,
    stakeholders,
    threshold,
    deployedAt: Math.floor(Date.now() / 1000),
    deployer: deployer.address,
  };
  const outputPath = path.join(deploymentsDir, `${networkName}.json`);
  fs.writeFileSync(outputPath, `${JSON.stringify(deployment, null, 2)}\n`);

  console.log("=== Deployment Summary ===");
  console.log(`Contract address: ${address}`);
  console.log(`Transaction hash: ${deploymentTx.hash}`);
  console.log(`Block number: ${receipt.blockNumber}`);
  console.log(`Gas used: ${receipt.gasUsed.toString()}`);
  console.log(`Stakeholders: ${stakeholders.join(", ")}`);
  console.log(`Threshold: ${threshold}`);
  console.log(`Deployment written to: ${outputPath}`);

  if (networkName === "sepolia") {
    const argsPath = writeVerifyArgs(deploymentsDir, networkName, stakeholders, threshold);
    const relativeArgsPath = path.relative(path.join(__dirname, ".."), argsPath);
    console.log(`Verify args written to: ${argsPath}`);
    console.log("To verify on Etherscan:");
    console.log(`npx hardhat verify --network sepolia ${address} --constructor-args ${relativeArgsPath}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
